services:
  elasticsearch:
    container_name: "elasticsearch_container"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    command:
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    container_name: "kibana_container"
    image: docker.elastic.co/kibana/kibana:8.12.1
    command:
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    volumes:
      - ./elastic_config/kibana.yml:/usr/share/elasticsearch/config/elasticsearch.yml
